name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          timeout: 60s
          command_timeout: 30m
          debug: true
          script: |
            echo "===== Connected ====="
            whoami
            hostname
            pwd

            if [ ! -d "/var/www/haxor-iptv" ]; then
              echo "Repository not found!"
              exit 1
            fi

            cd /var/www/haxor-iptv

            echo "===== Git ====="
            git fetch --all
            git reset --hard origin/main

            echo "===== Backend ====="
            cd backend
            npm install

            echo "===== Frontend ====="
            cd ../frontend
            npm install
            npm run build

            echo "===== Restart PM2 ====="
            cd ..

            if pm2 describe haxor-iptv-api > /dev/null; then
              pm2 restart haxor-iptv-api
            else
              pm2 start ecosystem.config.js
            fi

            pm2 save

            echo "===== Finished ====="